### ISSUE TITLE
Consider switching to MkDocs

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/springboot-migration-workshop#3]
> [MkDocs](https://www.mkdocs.org/) is a fast, simple and downright gorgeous static site generator that's geared towards building project documentation. Documentation source files are written in Markdown, and configured with a single YAML configuration file.

Was recommended MkDocs by a fellow speaker, who uses it in [their restassured-workshop](https://github.com/eliasnogueira/restassured-workshop-3h). Seems like with a single configuration file and some conventions we could get some useful and stylish benefits, as seen here: https://eliasnogueira.github.io/restassured-workshop-3h/

There's a few alternatives geared to generating documentation as well, via [awesome-static-generators#documentation](https://github.com/myles/awesome-static-generators#documentation).
- https://github.com/docsifyjs/docsify/
- https://github.com/facebook/docusaurus
- https://github.com/mkdocs/mkdocs/
- https://github.com/slatedocs/slate

That's already filtering out projects without recent releases or lack of a GitHub Pulse; judging by that docusaurus seems most active.

**Comment by okundzich** [comment]
please also talk to marketing, whatever SEO they are doing they are losing track of things as users/visitors go to our docs.

**Comment by timtebeek** [comment]
> please also talk to marketing, whatever SEO they are doing they are losing track of things as users/visitors go to our docs.

so while [Docusaurus has good support for SEO](https://docusaurus.io/docs/seo), this being a workshop that's infrequently used I don't think we ought to tie into tracking with the website. Definitely something to figure out if we're to replace GitBook, but not yet for the workshop alone. Would you agree there?

**Comment by okundzich** [comment]
optional. not sure the scope of work.  perhaps @mike-solomon can look into it if we decide to switch from gitbook.
